//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TOKEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TOKEN()
        {
            this.WALLET_X_TOKEN = new HashSet<WALLET_X_TOKEN>();
        }
    
        public int ID_TOKEN { get; set; }
        public Nullable<int> FK_CHAIN { get; set; }
        public string NAME { get; set; }
        public string CG_TICKER { get; set; }
        public string CONTRACT_ADDRESS { get; set; }
        public bool IS_NATIVE { get; set; }
    
        public virtual CHAIN CHAIN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WALLET_X_TOKEN> WALLET_X_TOKEN { get; set; }
    }
}
