//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class WALLET_X_TOKEN
    {
        public int ID_WALLET_X_TOKEN { get; set; }
        public int FK_WALLET { get; set; }
        public int FK_TOKEN { get; set; }
        public double TOKEN_BALANCE { get; set; }
    
        public virtual TOKEN TOKEN { get; set; }
        public virtual WALLET WALLET { get; set; }
    }
}
